/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.innowise.sivachenko.kafka.avro;
@org.apache.avro.specific.AvroGenerated
public enum AuditServiceType implements org.apache.avro.generic.GenericEnumSymbol<AuditServiceType> {
  CLIENT, CAR, RENT, PAYMENT, NOTIFICATION, AUDIT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AuditServiceType\",\"namespace\":\"com.innowise.sivachenko.kafka.avro\",\"symbols\":[\"CLIENT\",\"CAR\",\"RENT\",\"PAYMENT\",\"NOTIFICATION\",\"AUDIT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
