/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.innowise.sivachenko.kafka.avro;
@org.apache.avro.specific.AvroGenerated
public enum PaymentNotificationType implements org.apache.avro.generic.GenericEnumSymbol<PaymentNotificationType> {
  CREATE_PAYMENT, REFUND_PAYMENT, CHANGE_PAYMENT_STATUS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentNotificationType\",\"namespace\":\"com.innowise.sivachenko.kafka.avro\",\"symbols\":[\"CREATE_PAYMENT\",\"REFUND_PAYMENT\",\"CHANGE_PAYMENT_STATUS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
