version: "3.5"

networks:
  app-tier:
    name: app-tier
    driver: bridge

services:
  payment-db:
    image: mysql:8
    container_name: payment-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paymentdb
    volumes:
      - mysql_vlm:/var/lib/mysql
    networks:
      - app-tier

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8765:8080"
    networks:
      - app-tier


volumes:
  mysql_vlm: