server:
  port: 0

spring:
  application:
    name: payment-service
  profiles:
    active: test

  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/carsharing
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: kafka:29092
    properties:
      schema:
        registry:
          url: http://schema-registry:9091

kafka:
  topics:
    audit-topic:
      name: payment-service-audit-topic
    notification-topic:
      name: payment-service-notification-topic

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

stripe:
  secretkey: sk_test_51PByRIFeeS6BFRDaPlNszYd3ZRlciywD9CHoGDFMsJAZ4d8tnWnDUbOYas50p6lYRmDQlUnPgW1LNRVOLQ635oxH0081dj6qkr
  webhook:
    secret: whsec_41892afaf0e493e918af2c1df7be3b7b032ebc6a8489943c0df04a8bbbbc8be0

openapi:
  oAuthFlow:
    tokenUrl: http://localhost:8080/realms/carsharing/protocol/openid-connect/token
  service:
    name: payment-service
    version: 1.0.0
    description: Payment service for working with payments
    url: http://localhost:8088

springdoc:
  show-actuator: true
  api-docs:
    path: /payment-service/v3/api-docs
  swagger-ui:
    path: /payment-service/swagger-ui/index.html

feign:
  client:
    rent-service:
      name: rent-service

management:
  endpoints:
    web:
      exposure:
        include: '*'